DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS
(
    id           VARCHAR(36) PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    user_type    VARCHAR(20)  NOT NULL CHECK (user_type IN ('Outlaw', 'Sheriff')),
    bounty       INT                   DEFAULT 0,
    status       VARCHAR(50),
    salary       INT                   DEFAULT 0,
    captures     INT                   DEFAULT 0,
    eliminations INT                   DEFAULT 0
);

DROP TABLE IF EXISTS STUDENTS;
DROP TABLE IF EXISTS MATCHES;
DROP TABLE IF EXISTS CHAT_MESSAGES;

CREATE TABLE STUDENTS(
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    bio VARCHAR(255),
    photo VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE MATCHES(
    id VARCHAR(36) PRIMARY KEY,
    liker_id VARCHAR(36) NOT NULL,
    liked_id VARCHAR(36) NOT NULL,
    status VARCHAR(20) NOT NULL,
    FOREIGN KEY(liker_id) REFERENCES STUDENTS(id),
    FOREIGN KEY(liked_id) REFERENCES STUDENTS(id)
);

CREATE TABLE CHAT_MESSAGES(
    id VARCHAR(36) PRIMARY KEY,
    match_id VARCHAR(36) NOT NULL,
    sender_id VARCHAR(36) NOT NULL,
    content VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY(match_id) REFERENCES MATCHES(id),
    FOREIGN KEY(sender_id) REFERENCES STUDENTS(id)
);